on:
  # Trigger the workflow on push or pull request, but only for the develop branch
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # disable macos until #1797 is fixed
        #os: [macos-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.10]

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install MacOS system dependencies
        run: |
          brew install gtk+3 pygobject3
        if: matrix.os == 'macos-latest'

      - name: Install Ubuntu system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq -y gir1.2-gtk-3.0 gobject-introspection libgirepository1.0-dev xvfb
        if: matrix.os == 'ubuntu-latest'

      - name: Install Windows MSYS2
        uses: msys2/setup-msys2@v2
        if: matrix.os == 'windows-latest'

      - name: Install Windows system dependencies
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm git mingw-w64-x86_64-gtk3 mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-gobject
        if: matrix.os == 'windows-latest'

      - name: Install python dependencies
        run: |
          pip install PyGObject
          pip install pyxdg

      - name: Configure git (Ubuntu & MacOS)
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
        if: matrix.os != 'windows-latest'

      - name: Configure git (Windows)
        shell: msys2 {0}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
        if: matrix.os == 'windows-latest'

      - name: Test MacOS
        run: python3 ./test.py
        if: matrix.os == 'macos-latest'

      - name: Test Ubuntu
        run: xvfb-run ./test.py
        if: matrix.os == 'ubuntu-latest'

      - name: Test Windows
        shell: msys2 {0}
        run: python ./test.py
        if: matrix.os == 'windows-latest'
